server:
  port: 8711
spring:
#  profiles:
#    active: after_route
  application:
    name: gateway-8711

---
spring:
  profiles: admin-clinet
  boot:
    admin:
      client:
        url: http://localhost:8712
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: gateway-router
  cloud:
    gateway:
      discovery:
        locator:
#          表明gateway开启服务注册和发现的功能
          enabled: false
#          是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了）
          lowerCaseServiceId: true
      routes:
        - id: service-tk-8710
          uri: lb://service-tk-8710
          predicates:
            - Path=/tk/**
          filters:
            - StripPrefix=1
        - id: service-plus-8709
          uri: lb://service-plus-8709
          predicates:
            - Path=/plus/**
          filters:
            - StripPrefix=1
# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
---
spring:
  profiles: gateway-limiter
  cloud:
    gateway:
      routes:
        - id: limit_route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
  redis:
    host: localhost
    port: 6379
    database: 0

---
#spring:
#  profiles: after_route
#  cloud:
#    gateway:
#      routes:
#
#        - id: after_route
#          uri: http://httpbin.org:80/get
##          当请求的时间在这个配置的时间之后，请求会被路由到http://httpbin:org:80/get。:
#          predicates:
#            - After=2021-01-20T17:42:47.789-07:00[America/Denver]
##          熔断测试
#
#        - id: error_hystix
#          uri: http://127.0.0.1:8083/
#          predicates:
#            - Path=/feign/**
#          filters:
#            - StripPrefix=1 #去掉Path前缀,参数为1代表去掉/ribbon
#            - name: Hystrix
#              args:
#                name: test
#                fallbackUri: forward:/gateway/fallback

---
spring:
  cloud:
    gateway:
      routes:
        - id: before_route
          uri: http://example.org
          predicates:
            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]

---
spring:
  cloud:
    gateway:
      routes:
        - id: between_route
          uri: http://example.org
          predicates:
            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]

---
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://www.baidu.com
          predicates:
            - Cookie=chocolate, ch.p
          filters:
            - StripPrefix=1 #去掉Path前缀,参数为1代表去掉/ribbon
            - name: Hystrix
              args:
                name: test
                fallbackUri: forward:/gateway/fallback

---
spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://httpbin.org:80/get
          predicates:
            - Host=**.jermaine.com
          profiles: host_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: add_request_header_route
          uri: http://httpbin.org:80/get
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: add_request_header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: rewritepath_route
          uri: https://blog.csdn.net
          predicates:
            - Path=/foo/**
          filters:
            - RewritePath=/foo/(?<segment>.*), /$\{segment}
  profiles: rewritepath_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: elapse_route
          uri: http://httpbin.org:80/get
          filters:
            - RequestTime=false
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: elapse_route
