server:
  port: 8708
spring:
  profiles:
    active: common
  application:
    name: bus-8708

logging:
  level:
    cn.zm: debug

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
