##################### mybatis ###############################
mybatis:
  configuration:
    #配置驼峰下划线
    map-underscore-to-camel-case: true
    use-generated-keys: true
  typeAliasesPackage: cn.zm.netflix.mybatisplus.web.entity
  mapperLocations: classpath*:/mapper/**/*.xml
#mappers 多个接口时逗号隔开
mapper:
  mappers: cn.zm.tk.base.mapper.BaseMapper
  not-empty: true
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pagehelper:
    params: count=countSql
