#db config
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test_dev?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
      username: root
      password: root
      #连接池配置
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query-timeout: 60000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
      ###监控配置 begin###
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
        # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
      # 配置StatFilter
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
        # 配置WallFilter
        wall:
          enabled: false # 是否允许删除
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
##################### Druid ##################################
# 下面为连接池的补充设置，应用到上面所有数据源中
#spring:
#  datasource:
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
## 配置获取连接等待超时的时间
#    maxWait: 60000
## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
## 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis=: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
##这个过滤器有个小坑，会影响自定义批量sql，相关可以看我的另外一篇文章https://blog.csdn.net/cmw1085215666/article/details/101380207
#    filters: stat,wall,log4j
#    logSlowSql: true