server:
  port: 8080
spring:
  application:
    name: security
  security:
    user:
      name: user
      password: user
  profiles:
    active: plus, common, datasource
jwt:
  token:
    prefix: "Bearer "
  admin: admin
  secret: jermaine_secret # 千万不能使用中文.
  ignore: /doc.html,/webjars/**,/favicon.ico,/swagger-resources/**,/v2/api-docs/**,/v2/api-docs**,/security/not/authentication,/jwt/authenticate,/jwt/register,/authenticated