server:
  port: 8706
spring:
  profiles:
    active: common
  application:
    name: Zuul-8706

# ========添加配置=======
management:
  endpoints:
    web:
      exposure:
        include: "*" #注意这里*要加引号，暴露全部，也可以只暴露相应endpoint
  endpoint:
    routes:
      enabled: true # 默认为true，可以省略

# 如果不配置, zuul会自动根据eureka上的实例配置.
#zuul:
#  routes:
#    ribbon-8703:
#      path: /ribbon-8703/**
#      serviceId: ribbon-8703
#    service-app:
#      path: /service-app/**
#      serviceId: service-app

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
logging:
  level:
    cn.zm: debug
