server:
  port: 8702
spring:
  profiles:
    active: common, plus
  application:
    name: netflix-mybatisplus-app-ribbon-8702

logging:
  level:
    cn.zm: debug

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
