server:
  port: 8710
spring:
  profiles:
    active: common, tk
  application:
    name: service-tk-8710
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    cn.zm: debug

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/

