server:
  port: 8701
spring:
  profiles:
    active: common, plus
#eureka:
#  instance:
#    hostname: eureka-server
#  client:
## 通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:

#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/