server:
  port: 8709
spring:
  profiles:
    active: common, plus
  application:
    name: service-plus-8709
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    cn.zm: debug

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
global:
  config:
    foo:
      bar: hello world
  netty:
    foo:
      bar: hello world