##db config
#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#      username: root
#      password: root
#      #连接池配置
#      initial-size: 5
#      max-active: 100
#      min-idle: 5
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      validation-query-timeout: 60000
#      validation-query: SELECT 1 FROM DUAL
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 100000
#      ###监控配置 begin###
#      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
#        # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: false
#        login-username: admin
#        login-password: admin
#        allow: 127.0.0.1
#      # 配置StatFilter
#      filter:
#        stat:
#          db-type: mysql
#          log-slow-sql: true
#          slow-sql-millis: 5000
#        # 配置WallFilter
#        wall:
#          enabled: false # 是否允许删除
#          db-type: mysql
#          config:
#            delete-allow: false
#            drop-table-allow: false
##knife4j:
##  basic:
##    enable: true