server:
  port: 8718
spring:
  application:
    name: Sentinel-8718
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8090