server:
  port: 8701
spring:
  profiles:
    active: common, plus
  application:
    name: service-app

logging:
  level:
    cn.zm: debug

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
