server:
  port: 8704
spring:
  profiles:
    active: common
  application:
    name: feign-8704

logging:
  level:
    cn.zm: debug

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
