################# mybatis #################
mybatis:
  configuration:
    #配置驼峰下划线
    map-underscore-to-camel-case: true
    use-generated-keys: true
#  typeAliasesPackage: cn.zm.netflix.mybatisplus.web.entity
  mapperLocations: classpath*:/mapper/**/*.xml

################# pagehelper #################
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
